FROM pytorch/pytorch:2.4.0-cuda12.4-cudnn9-runtime

# Prevent prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    libatlas-base-dev \
    liblapack-dev \
    libblas-dev \
    gfortran \
    iptables \
    && rm -rf /var/lib/apt/lists/*

# Set a non-root user for security
RUN useradd -m miner

# Set environment variables
ENV PATH="/home/miner/.local/bin:${PATH}" \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=300 \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false

# Copy all of deval over and initialize
WORKDIR /app

COPY --chown=miner:miner . ./

ENTRYPOINT ["deval/api/docker_init.sh"]

COPY --chown=miner:miner deval/api/pyproject.toml deval/api/poetry.lock ./
RUN pip install poetry
RUN POETRY_VIRTUALENVS_CREATE=false poetry install --only main -vvv --no-root


# grant access only to working directory and temp directory
RUN mkdir /app/logs
RUN mkdir -p /tmp && chmod 1777 /tmp
RUN mkdir -p /app/eval_llm
RUN chmod -R 777 /app

ENV TMPDIR=/tmp
ENV HF_HOME=/app/eval_llm/.cache/huggingface


# switch to non-root user
USER miner

# Start API
EXPOSE 8000
CMD ["poetry", "run", "uvicorn", "deval.api.miner_api:app", "--host", "0.0.0.0", "--port", "8000"]