version: '3.8'

services:
  miner-api:
    build:
      context: .
      dockerfile: deval/api/dockerfile
    container_name: miner-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_URL=${MODEL_URL}
    user: "miner"
    security_opt:
      - no-new-privileges  # Prevent privilege escalation
    cap_drop:
      - ALL  # Drop all unnecessary capabilities
    cap_add:
      - NET_BIND_SERVICE  # Allow binding to network services for internal comms
    networks:
      - restricted_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


networks:
  restricted_net:
    driver: bridge