version: '3.8'

services:
  miner-api:
    build:
      context: .
      dockerfile: deval/api/dockerfile
    container_name: miner-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_URL=${MODEL_URL}
    security_opt:
      - no-new-privileges  
    cap_drop:
      - ALL  
    cap_add:
      - NET_BIND_SERVICE  
      - NET_ADMIN
      - NET_RAW
      - SETUID
      - SETGID
    networks:
      - restricted_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


networks:
  restricted_net:
    driver: bridge